/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AyudaRouteImport } from './routes/ayuda'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ConfirmacionRouteImport } from './routes/confirmacion'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CuentaRouteImport } from './routes/cuenta'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MiPlatoRouteImport } from './routes/mi-plato'
import { Route as NotificacionesRouteImport } from './routes/notificaciones'
import { Route as PagoRouteImport } from './routes/pago'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as RecuperarRouteImport } from './routes/recuperar'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as ChatCocineroIdRouteImport } from './routes/chat.$cocineroId'
import { Route as CocineroIdRouteImport } from './routes/cocinero.$id'
import { Route as ProductoIdRouteImport } from './routes/producto.$id'
import { Route as PedidoIdIndexRouteImport } from './routes/pedido.$id.index'
import { Route as PedidoIdCalificarRouteImport } from './routes/pedido.$id.calificar'
import { Route as PedidoIdReclamoRouteImport } from './routes/pedido.$id.reclamo'
import { Route as ProductoIdOpinionesRouteImport } from './routes/producto.$id.opiniones'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AyudaRoute = AyudaRouteImport.update({
  id: '/ayuda',
  path: '/ayuda',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmacionRoute = ConfirmacionRouteImport.update({
  id: '/confirmacion',
  path: '/confirmacion',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CuentaRoute = CuentaRouteImport.update({
  id: '/cuenta',
  path: '/cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MiPlatoRoute = MiPlatoRouteImport.update({
  id: '/mi-plato',
  path: '/mi-plato',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacionesRoute = NotificacionesRouteImport.update({
  id: '/notificaciones',
  path: '/notificaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const PagoRoute = PagoRouteImport.update({
  id: '/pago',
  path: '/pago',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarRoute = RecuperarRouteImport.update({
  id: '/recuperar',
  path: '/recuperar',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatCocineroIdRoute = ChatCocineroIdRouteImport.update({
  id: '/chat/$cocineroId',
  path: '/chat/$cocineroId',
  getParentRoute: () => rootRouteImport,
} as any)
const CocineroIdRoute = CocineroIdRouteImport.update({
  id: '/cocinero/$id',
  path: '/cocinero/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoIdRoute = ProductoIdRouteImport.update({
  id: '/producto/$id',
  path: '/producto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoIdIndexRoute = PedidoIdIndexRouteImport.update({
  id: '/pedido/$id/',
  path: '/pedido/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoIdCalificarRoute = PedidoIdCalificarRouteImport.update({
  id: '/pedido/$id/calificar',
  path: '/pedido/$id/calificar',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoIdReclamoRoute = PedidoIdReclamoRouteImport.update({
  id: '/pedido/$id/reclamo',
  path: '/pedido/$id/reclamo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoIdOpinionesRoute = ProductoIdOpinionesRouteImport.update({
  id: '/opiniones',
  path: '/opiniones',
  getParentRoute: () => ProductoIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ayuda': typeof AyudaRoute
  '/buscar': typeof BuscarRoute
  '/checkout': typeof CheckoutRoute
  '/confirmacion': typeof ConfirmacionRoute
  '/contacto': typeof ContactoRoute
  '/cuenta': typeof CuentaRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/mi-plato': typeof MiPlatoRoute
  '/notificaciones': typeof NotificacionesRoute
  '/pago': typeof PagoRoute
  '/pedidos': typeof PedidosRoute
  '/privacidad': typeof PrivacidadRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/terminos': typeof TerminosRoute
  '/chat/$cocineroId': typeof ChatCocineroIdRoute
  '/cocinero/$id': typeof CocineroIdRoute
  '/producto/$id': typeof ProductoIdRouteWithChildren
  '/pedido/$id/calificar': typeof PedidoIdCalificarRoute
  '/pedido/$id/reclamo': typeof PedidoIdReclamoRoute
  '/producto/$id/opiniones': typeof ProductoIdOpinionesRoute
  '/pedido/$id/': typeof PedidoIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ayuda': typeof AyudaRoute
  '/buscar': typeof BuscarRoute
  '/checkout': typeof CheckoutRoute
  '/confirmacion': typeof ConfirmacionRoute
  '/contacto': typeof ContactoRoute
  '/cuenta': typeof CuentaRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/mi-plato': typeof MiPlatoRoute
  '/notificaciones': typeof NotificacionesRoute
  '/pago': typeof PagoRoute
  '/pedidos': typeof PedidosRoute
  '/privacidad': typeof PrivacidadRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/terminos': typeof TerminosRoute
  '/chat/$cocineroId': typeof ChatCocineroIdRoute
  '/cocinero/$id': typeof CocineroIdRoute
  '/producto/$id': typeof ProductoIdRouteWithChildren
  '/pedido/$id/calificar': typeof PedidoIdCalificarRoute
  '/pedido/$id/reclamo': typeof PedidoIdReclamoRoute
  '/producto/$id/opiniones': typeof ProductoIdOpinionesRoute
  '/pedido/$id': typeof PedidoIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ayuda': typeof AyudaRoute
  '/buscar': typeof BuscarRoute
  '/checkout': typeof CheckoutRoute
  '/confirmacion': typeof ConfirmacionRoute
  '/contacto': typeof ContactoRoute
  '/cuenta': typeof CuentaRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/mi-plato': typeof MiPlatoRoute
  '/notificaciones': typeof NotificacionesRoute
  '/pago': typeof PagoRoute
  '/pedidos': typeof PedidosRoute
  '/privacidad': typeof PrivacidadRoute
  '/recuperar': typeof RecuperarRoute
  '/registro': typeof RegistroRoute
  '/terminos': typeof TerminosRoute
  '/chat/$cocineroId': typeof ChatCocineroIdRoute
  '/cocinero/$id': typeof CocineroIdRoute
  '/producto/$id': typeof ProductoIdRouteWithChildren
  '/pedido/$id/calificar': typeof PedidoIdCalificarRoute
  '/pedido/$id/reclamo': typeof PedidoIdReclamoRoute
  '/producto/$id/opiniones': typeof ProductoIdOpinionesRoute
  '/pedido/$id/': typeof PedidoIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ayuda'
    | '/buscar'
    | '/checkout'
    | '/confirmacion'
    | '/contacto'
    | '/cuenta'
    | '/favoritos'
    | '/login'
    | '/mi-plato'
    | '/notificaciones'
    | '/pago'
    | '/pedidos'
    | '/privacidad'
    | '/recuperar'
    | '/registro'
    | '/terminos'
    | '/chat/$cocineroId'
    | '/cocinero/$id'
    | '/producto/$id'
    | '/pedido/$id/calificar'
    | '/pedido/$id/reclamo'
    | '/producto/$id/opiniones'
    | '/pedido/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ayuda'
    | '/buscar'
    | '/checkout'
    | '/confirmacion'
    | '/contacto'
    | '/cuenta'
    | '/favoritos'
    | '/login'
    | '/mi-plato'
    | '/notificaciones'
    | '/pago'
    | '/pedidos'
    | '/privacidad'
    | '/recuperar'
    | '/registro'
    | '/terminos'
    | '/chat/$cocineroId'
    | '/cocinero/$id'
    | '/producto/$id'
    | '/pedido/$id/calificar'
    | '/pedido/$id/reclamo'
    | '/producto/$id/opiniones'
    | '/pedido/$id'
  id:
    | '__root__'
    | '/'
    | '/ayuda'
    | '/buscar'
    | '/checkout'
    | '/confirmacion'
    | '/contacto'
    | '/cuenta'
    | '/favoritos'
    | '/login'
    | '/mi-plato'
    | '/notificaciones'
    | '/pago'
    | '/pedidos'
    | '/privacidad'
    | '/recuperar'
    | '/registro'
    | '/terminos'
    | '/chat/$cocineroId'
    | '/cocinero/$id'
    | '/producto/$id'
    | '/pedido/$id/calificar'
    | '/pedido/$id/reclamo'
    | '/producto/$id/opiniones'
    | '/pedido/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AyudaRoute: typeof AyudaRoute
  BuscarRoute: typeof BuscarRoute
  CheckoutRoute: typeof CheckoutRoute
  ConfirmacionRoute: typeof ConfirmacionRoute
  ContactoRoute: typeof ContactoRoute
  CuentaRoute: typeof CuentaRoute
  FavoritosRoute: typeof FavoritosRoute
  LoginRoute: typeof LoginRoute
  MiPlatoRoute: typeof MiPlatoRoute
  NotificacionesRoute: typeof NotificacionesRoute
  PagoRoute: typeof PagoRoute
  PedidosRoute: typeof PedidosRoute
  PrivacidadRoute: typeof PrivacidadRoute
  RecuperarRoute: typeof RecuperarRoute
  RegistroRoute: typeof RegistroRoute
  TerminosRoute: typeof TerminosRoute
  ChatCocineroIdRoute: typeof ChatCocineroIdRoute
  CocineroIdRoute: typeof CocineroIdRoute
  ProductoIdRoute: typeof ProductoIdRouteWithChildren
  PedidoIdCalificarRoute: typeof PedidoIdCalificarRoute
  PedidoIdReclamoRoute: typeof PedidoIdReclamoRoute
  PedidoIdIndexRoute: typeof PedidoIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayuda': {
      id: '/ayuda'
      path: '/ayuda'
      fullPath: '/ayuda'
      preLoaderRoute: typeof AyudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmacion': {
      id: '/confirmacion'
      path: '/confirmacion'
      fullPath: '/confirmacion'
      preLoaderRoute: typeof ConfirmacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuenta': {
      id: '/cuenta'
      path: '/cuenta'
      fullPath: '/cuenta'
      preLoaderRoute: typeof CuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-plato': {
      id: '/mi-plato'
      path: '/mi-plato'
      fullPath: '/mi-plato'
      preLoaderRoute: typeof MiPlatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificaciones': {
      id: '/notificaciones'
      path: '/notificaciones'
      fullPath: '/notificaciones'
      preLoaderRoute: typeof NotificacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pago': {
      id: '/pago'
      path: '/pago'
      fullPath: '/pago'
      preLoaderRoute: typeof PagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar': {
      id: '/recuperar'
      path: '/recuperar'
      fullPath: '/recuperar'
      preLoaderRoute: typeof RecuperarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$cocineroId': {
      id: '/chat/$cocineroId'
      path: '/chat/$cocineroId'
      fullPath: '/chat/$cocineroId'
      preLoaderRoute: typeof ChatCocineroIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cocinero/$id': {
      id: '/cocinero/$id'
      path: '/cocinero/$id'
      fullPath: '/cocinero/$id'
      preLoaderRoute: typeof CocineroIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto/$id': {
      id: '/producto/$id'
      path: '/producto/$id'
      fullPath: '/producto/$id'
      preLoaderRoute: typeof ProductoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$id/': {
      id: '/pedido/$id/'
      path: '/pedido/$id'
      fullPath: '/pedido/$id/'
      preLoaderRoute: typeof PedidoIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$id/calificar': {
      id: '/pedido/$id/calificar'
      path: '/pedido/$id/calificar'
      fullPath: '/pedido/$id/calificar'
      preLoaderRoute: typeof PedidoIdCalificarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$id/reclamo': {
      id: '/pedido/$id/reclamo'
      path: '/pedido/$id/reclamo'
      fullPath: '/pedido/$id/reclamo'
      preLoaderRoute: typeof PedidoIdReclamoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto/$id/opiniones': {
      id: '/producto/$id/opiniones'
      path: '/opiniones'
      fullPath: '/producto/$id/opiniones'
      preLoaderRoute: typeof ProductoIdOpinionesRouteImport
      parentRoute: typeof ProductoIdRoute
    }
  }
}

interface ProductoIdRouteChildren {
  ProductoIdOpinionesRoute: typeof ProductoIdOpinionesRoute
}

const ProductoIdRouteChildren: ProductoIdRouteChildren = {
  ProductoIdOpinionesRoute: ProductoIdOpinionesRoute,
}

const ProductoIdRouteWithChildren = ProductoIdRoute._addFileChildren(
  ProductoIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AyudaRoute: AyudaRoute,
  BuscarRoute: BuscarRoute,
  CheckoutRoute: CheckoutRoute,
  ConfirmacionRoute: ConfirmacionRoute,
  ContactoRoute: ContactoRoute,
  CuentaRoute: CuentaRoute,
  FavoritosRoute: FavoritosRoute,
  LoginRoute: LoginRoute,
  MiPlatoRoute: MiPlatoRoute,
  NotificacionesRoute: NotificacionesRoute,
  PagoRoute: PagoRoute,
  PedidosRoute: PedidosRoute,
  PrivacidadRoute: PrivacidadRoute,
  RecuperarRoute: RecuperarRoute,
  RegistroRoute: RegistroRoute,
  TerminosRoute: TerminosRoute,
  ChatCocineroIdRoute: ChatCocineroIdRoute,
  CocineroIdRoute: CocineroIdRoute,
  ProductoIdRoute: ProductoIdRouteWithChildren,
  PedidoIdCalificarRoute: PedidoIdCalificarRoute,
  PedidoIdReclamoRoute: PedidoIdReclamoRoute,
  PedidoIdIndexRoute: PedidoIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
